
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvfnmptlusnsguzkgeql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Zm5tcHRsdXNuc2d1emtnZXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDk2NjYsImV4cCI6MjA1ODIyNTY2Nn0.4lOjOT8rVQFYevi7BvUHfCvQcmdG3v3JHGdH9xkmex4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
